[server]
address = "127.0.0.1"
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#18181b"
backgroundColor = "#fafafa"
secondaryBackgroundColor = "#f4f4f5"
textColor = "#18181b"
font = "sans serif"
baseFontSize = 14
